# Generated by Django 5.0 on 2024-05-07 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mode1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('gmail', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'user_data',
            },
        ),
    ]
